name: C/C++ CI

on:
  push:
    branches: [ master ,  utf8 ]
  pull_request:
    branches: [ master ,  utf8 ]
  delete:
    branches: [ master ,  utf8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodule
      run: git submodule update --init
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: make bin
      run: make bin
    - name: make test
      run: make test
      
      

